#ifndef MS449_TESTING
#define MS449_TESTING

#include <iostream>
#include <string>
#include <vector>
#include <functional>
#include <chrono>

namespace testing {
	using namespace std;

	/// <summary>
	/// A implimentation of a basic unit testing framework.
	/// </summary>
	class UnitTest {
	public:
		/// <summary>
		/// A object representing the result of a unit test. 
		/// </summary>
		class TestResult {
		public:
			/// <summary>
			/// Name of the test which the result was generated by.
			/// </summary>
			string name;

			/// <summary>
			/// If the test passed.
			/// </summary>
			bool passed;

			/// <summary>
			/// How long the test took to run in microseconds.
			/// </summary>
			chrono::microseconds durration;

			/// <summary>
			/// Create an instance of TestResult
			/// </summary>
			/// <param name="name">Name of the test generating the result.</param>
			/// <param name="passed">If the test passed.</param>
			TestResult(string name, bool passed, chrono::microseconds durration = chrono::microseconds(0)) {
				this->name = name;
				this->passed = passed;
				this->durration = durration;
			}
		};

	private:
		/// <summary>
		/// Name of the UnitTest instance.
		/// </summary>
		string name;

		/// <summary>
		/// Vector containing results of the UnitTest instance.
		/// </summary>
		vector<TestResult> results;

		/// <summary>
		/// The stream to which logs are sent.
		/// </summary>
		ostream& log_stream = cout;

		/// <summary>
		/// Log the result of a test.
		/// </summary>
		void log_test(string testName, bool testPassed, chrono::microseconds testDurration = chrono::microseconds(0)) {
			results.push_back(TestResult(testName, testPassed, testDurration));
		}

	public:
		/// <summary>
		/// Construct and instance of unit test with a given name.
		/// </summary>
		/// <param name="name">Name of the UnitTest instance.</param>
		UnitTest(string name = "Unit Test", ostream& log_stream = cout) {
			this->name = name;
		}

		/// <summary>
		/// Log a value to the specified loging stream given a optional test name.
		/// </summary>
		/// <param name="message">Message to be logged.</param>
		/// <param name="testName">Name of the test log is sent from (if applicalbe)</param>
		void log(string message, string testName = "") {
			cout << "[" << this->name << "]" << (testName.empty() ? "" : ("(" + testName + ")")) << ": " << message << endl;
		}

		/// <summary>
		/// Assert that the first value provided is the same as the second expected value.
		/// </summary>
		/// <typeparam name="T">Type of the value being compared.</typeparam>
		/// <param name="name">Name of the test being performed.</param>
		/// <param name="value">Value being compared to the expected value.</param>
		/// <param name="expected">What the value provided is expected to be.</param>
		template <typename T> void assert(string name, T value, T expected) {
			this->log_test(name, value == expected);
		}

		/// <summary>
		/// Run a test asserting that the value return by the provided function is equal to the expected value.
		/// </summary>
		/// <typeparam name="T">Type of the value being compared.</typeparam>
		/// <param name="name">Name of the test being performed.</param>
		/// <param name="test">Function which returns a value.</param>
		/// <param name="expected">What the value returned by the function is expected to be.</param>
		template <typename T> void assert(string name, function<T()> test, T expected) {
			try {
				//run the function and get the result & measure how long it takes
				auto start = chrono::high_resolution_clock::now();
				T result = test();
				auto end = chrono::high_resolution_clock::now();

				//get execution durration
				auto durration = chrono::duration_cast<chrono::microseconds>(end - start);

				//log the result
				this->log_test(name, result == expected, durration);
			}
			catch (const std::exception& e) {
				this->log("Unhandled Exception: " + *e.what(), name);
				results.push_back(TestResult("[EXCEPTION]" + name, false));
			}
		}

		/// <summary>
		/// Checks all performed tests to see if any failed, if all passed true is returned, otherwise false.
		/// </summary>
		/// <returns>If all tests passed.</returns>
		bool passed() {
			for (auto result : this->results) {
				if (!result.passed) return false;
			}

			return true;
		}

		/// <summary>
		/// Log the results of the unit test to the specified stream.
		/// </summary>
		void log_results(ostream& stream = cout) {
			stream << "+-" << string(this->name.length(), '-') << "---------+" << endl;
			stream << "| " << this->name << " Results |" << endl;
			stream << "+-" << string(this->name.length(), '-') << "---------+" << endl;
			stream << "|" << endl;

			//log the result of each test
			for (int i = 0; i < this->results.size(); i++) {
				auto result = this->results[i];

				//log test result (pass/fail)
				stream << "| (#" << (i + 1) << ")[" << (result.passed ? "PASSED" : "FAILED") << "]: " << result.name << endl;

				//log test durration if not 0
				if (result.durration != chrono::microseconds(0)) stream << "|   <> Test took " << result.durration.count() << "ms <>" << endl;

				stream << "|" << endl;
			}

			//get number of tests, passed tests, and durration of all tests combined
			int totalTests = this->results.size();
			int totalPassedTests = 0;
			chrono::microseconds totalDurration = chrono::microseconds(0);

			for (auto result : this->results) {
				if (result.passed) totalPassedTests += 1;
				totalDurration += result.durration;
			}

			stream << "+\\" << endl;
			stream << "|| <> RESULT <>" << endl;
			stream << "|| - " << (this->passed() ? "TEST PASSED" : "TEST FAILED") << endl;
			stream << "|| - " << totalPassedTests << "/" << totalTests << " Tests Passed" << endl;
			stream << "|| - " << "Tests took " << totalDurration.count() << "ms in total" << endl;
			stream << "+/" << endl;
		}
	};
}

#endif